FROM ruby:3.3

WORKDIR /app

RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    default-mysql-client
    
RUN apt-get update -qq && apt-get install -y default-mysql-client

COPY Gemfile* ./
RUN gem install bundler && bundle install

COPY . .

EXPOSE 3000

CMD ["bash", "-c", "bundle exec rails db:create db:migrate && bundle exec rails s -b 0.0.0.0 -p 3000"]
